---
title: "Initial_Data_Visualization"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(here)
library(viridis)
```

```{r load data}
#read in CA data from processed folder 
outage_group_CA <- read.csv(here('Data/Processed/outage_group_CA.csv'), 
                            stringsAsFactors = TRUE)

#update date object to date format 
outage_group_CA$date <- ymd(outage_group_CA$date)

```

```{r CA data visualization}

mytheme <- theme_classic(base_size = 12) +
  theme(axis.text = element_text(color = "black"))
theme_set(mytheme)

#processing: plots, time plot, county spatial plot? 

#yearly plot 
CA_yearly <- outage_group_CA %>% 
  ggplot(
    mapping = aes(
      x= date,
      y = outage_count
      )) +
  geom_point(size = 2, alpha = 0.7)+
  geom_line()+
  geom_smooth(method ="lm", se = FALSE) +
  labs(
    title = "Number of Power Outages in California from 2015 to 2023",
    y = "Number of Outages",
    x = "Year"
  )

CA_yearly

#monthly plot (for data visualization)
CA_monthly_plot <- outage_group_CA %>% 
  ggplot(
    mapping = aes(
      x=factor(
      month,
      levels=1:12,
      labels=month.abb),
      y = outage_count,
      color = year)
    ) +
 geom_point(size = 2, alpha = 0.7)+
 scale_color_viridis(
   option = "mako", 
   direction = -1)+
  labs(
    title = "Number of Power Outages in California by Month from 2015 to 2023",
    y = "Number of Outages",
    x = "Month",
    color = "Year",
  )

CA_monthly_plot

CA_monthly_duration_plot <- outage_group_CA %>% 
  ggplot(
    mapping = aes(
      x=factor(
      month,
      levels=1:12,
      labels=month.abb),
      y = max_outage_duration,
      color = year)
    ) +
 geom_point(size = 2, alpha = 0.7)+
 scale_color_viridis(
   option = "mako", 
   direction = -1)+
  labs(
    title = "Maximum Duration of Power Outages in California by Month from 2015 to 2023",
    y = "Maximum Outage Duration (hours)",
    x = "Month",
    color = "Year",
  )

CA_monthly_duration_plot 

CA_weighted_customers_plot <- outage_group_CA %>% 
  ggplot(
    mapping = aes(
      x=factor(
      month,
      levels=1:12,
      labels=month.abb),
      y = customer_weighted_hours,
      color = year)
    ) +
 geom_point(size = 2, alpha = 0.7)+
 scale_color_viridis(
   option = "mako", 
   direction = -1)+
  labs(
    title = "Customer Weighted Hours of Power Outages in California by Month from 2015 to 2023",
    y = "Customer Weighted Hours",
    x = "Month",
    color = "Year",
  )

CA_weighted_customers_plot

```

