---
title: "Data_Analysis_TX"
author: Carina Huang
output: html_document
---

```{r setup, include=FALSE}
# Load your packages
library(tidyverse)
library(here)
library(lubridate)
library(viridis)
library(zoo)
library(trend)
library(Kendall)
library(cowplot)
library(knitr)
library(kableExtra)

here()

# Set ggplot theme
mytheme <- theme_classic(base_size = 10) +
  theme(plot.title = element_text(size = 11, hjust = 0.5, face = "bold"),
        axis.title.x = element_text(size = 10.5),
        axis.title.y = element_text(size = 10.5))
theme_set(mytheme)

knitr::opts_chunk$set(
  echo = FALSE,      # hide all code
  warning = FALSE,   # hide warnings
  message = FALSE,   # hide messages
  fig.align = "center") #center figures 

#load TX data
outage_group_TX <- read.csv(here('Data/Processed/outage_group_TX.csv'))
outage_group_TX$date <- ymd(outage_group_TX$date)

```

```{r txyearly, fig.cap="Yearly plot of power outages in Texas from 2015-2023."}
TX_outage_count <- ggplot(outage_group_TX,
                          aes(x = date,
                              y = outage_count))+
  geom_point(size = 2, alpha = 0.7)+
  geom_line()+
  geom_smooth(method = "lm", se = FALSE, color = "blue")+
  ylim(0,3000)+
  labs(title = "Number of Power Outages in Texas from 2015-2023",
       x = "Year",
       y="Number of Outages")

TX_outage_count
```

```{r txmonthly, fig.cap="Monthly plot of power outages in Texas from 2015 to 2023."}
TX_outage_count_month <- outage_group_TX %>% 
  ggplot(aes(x = factor(month,
                        levels=1:12,
                        labels=month.abb),
                             y = outage_count,
                             color = factor(year)))+
  geom_point(size = 2, alpha = 0.7)+
  scale_colour_viridis(option = "mako", direction = -1, discrete = TRUE)+
  labs(title = "Number of Power Outages in Texas by Month from 2015-2023",
       x = "Month",
       y="Number of Outages", 
       color = "Year")

TX_outage_count_month
```

```{r txtimeseries, fig.cap="Decomposed components of the Texas power outage count time series."}
#time series object
TXOutage_count_ts <- ts(outage_group_TX$outage_count, 
                      start = c(2015,1), 
                      end = c(2023, 12),
                      frequency = 12)

# Generate the decomposition
TXOutage_count_Decomposed <- stl(TXOutage_count_ts, s.window = "periodic")
# Visualize the decomposed series. 
plot(TXOutage_count_Decomposed)
```

```{r TXtrend, fig.cap="Trend versus observation of power outages in Texas (2015-2023)."}
# Extract the components and turn them into data frames
TXOutage_count_Components <- as.data.frame(TXOutage_count_Decomposed$time.series[,1:3])

TXOutage_count_Components <- mutate(TXOutage_count_Components,
        Observed = outage_group_TX$outage_count, 
        Month = outage_group_TX$month,
        Date = outage_group_TX$date)

# Visualize how the trend maps onto the data
ggplot(TXOutage_count_Components) +
  geom_line(aes(y = Observed, x = Date),  size = 0.25) +
  geom_line(aes(y = trend, x = Date), color = "blue") +
  geom_hline(yintercept = 0, lty = 2)+
  ylim(-100,3000)+
  labs(title = "Trend Component of the Texas Power Outage ",
       x = "Year",
       y=" Number of Outages ")
```

```{r TXseasonal, fig.cap="Seasonality component of the Texas power outage count time series analysis where yearly data is grouped by month."}
# Visualize how the seasonal cycle maps onto the data
ggplot(TXOutage_count_Components) +
  geom_line(aes(y = seasonal, 
                x=factor(Month, levels=1:12, labels=month.abb), 
                group = year(Date)), 
                color = "blue") +
  geom_hline(yintercept = 0, lty = 2) +
  labs(x = "Month", 
       y = "# of outages",
       title = "Seasonality of Power Outages in Texas")
```

```{r TX seasonal ANOVA, include=FALSE}
##Are outage counts significantly different across months?
##Null Hypothesis: Mean outage counts are the same for all 12 months 
##Alt Hypothesis: At least on month differs (Seasonality)
#format month as factor
outage_group_TX$month <- factor(month(outage_group_TX$date),
                                levels = 1:12,
                                labels = month.abb)

#run anova
TX_anova_outage <- aov(data = outage_group_TX, outage_count ~ month)
summary(TX_anova_outage)

#show months
TukeyHSD(TX_anova_outage)

#despite visual apperances of a trend, with power outages peaking in May...
#The frequency of outages in Texas was not significantly different among the months (ANOVA; df = 11, F = 1.215, p < 0.288).  

```

```{r}
TX_outage_weighted <- outage_group_TX %>% 
  ggplot(aes(x = factor(month,
                        levels=month.abb,
                        labels=month.abb),
                             y = customer_weighted_hours,
                             color = year))+
  geom_point(size = 2, alpha = 0.7)+
  scale_colour_viridis(option = "mako", direction = -1)+
  labs(title = "Weighted Outage Duration in Texas from 2015-2023 \n (# of customers * outage time) ",
       x = "Month",
       y="Outage Duration (min) ")+
  ylim(0,50000000)
  
TX_outage_weighted
```

```{r txtimeseriesweighted, fig.cap="Decomposed components of customer power outage time in Texas (2015-2023)."}
#time series object
TX_CWH_ts <- ts(outage_group_TX$customer_weighted_hours, 
                      start = c(2015,1), 
                      end = c(2023, 12),
                      frequency = 12)

# Generate the decomposition
TX_CWH_ts_Decomposed <- stl(TX_CWH_ts, s.window = "periodic")
# Visualize the decomposed series. 
plot(TX_CWH_ts_Decomposed)
```


```{r TXCWHtrend, fig.cap="Trend versus observation of customer power outages in Texas (2015-2023)."}
# Extract the components and turn them into data frames
TX_CWH_Components <- as.data.frame(TX_CWH_ts_Decomposed$time.series[,1:3]) %>% 
  mutate(
        Observed = outage_group_TX$customer_weighted_hours, 
        Month = outage_group_TX$month,
        Date = outage_group_TX$date)

# Visualize how the trend maps onto the data
ggplot(TX_CWH_Components) +
  geom_line(aes(y = Observed, x = Date),  size = 0.25) +
  geom_line(aes(y = trend, x = Date), color = "blue") +
  geom_hline(yintercept = 0, lty = 2)+
  labs(title = "Trend versus observation of power outages in Texas (2015-2023)",
       x = "Year",
       y=" Number of Outages ")

```


```{r}
#Mann-Kendall Seasonality Test
TX_CWH_SMK <- Kendall::SeasonalMannKendall(TX_CWH_ts)
TX_CWH_SMK
summary(TX_CWH_SMK)

#p-value = 5.3438e-11

#Remove Seasonal
TX_CWH_noseas <- TX_CWH_ts - TX_CWH_Components$seasonal
TX_CWH_nonseason <- trend::mk.test(TX_CWH_noseas)
TX_CWH_nonseason
```

```{r TXCWHseason, fig.cap="Seasonal component of customer weighted outage hours in Texas}
# Visualize how the seasonal cycle maps onto the data
ggplot(TX_CWH_Components) +
  geom_line(aes(y = seasonal, 
                x=factor(Month, levels=month.abb, labels=month.abb), 
                group = year(Date)), 
                color = "blue") +
  geom_hline(yintercept = 0, lty = 2) +
  labs(x = "Month", 
       y = "# of outages",
       title = "Seasonality of Customer Weighted Outages Hours in Texas, 2015-2023")
```

