---
title: "Data_Wrang_TX"
output: html_document
---

```{r set up and import libraries}
library(tidyverse)
library(lubridate)
library(here)
library(viridis)
library(RColorBrewer)
library(ggplot2)
library(Kendall)
library(tseries)
library(zoo)


here()
```

```{r read csv}

outage_group_all_years <- read.csv(here('Data/Processed/outage_group_all_years.csv'), stringsAsFactors = TRUE)

#Finding TX
outage_group_TX <- outage_group_all_years %>% 
  filter(state == 'TX') %>% 
  mutate(date = my(paste0(month, "-", year)))

```

```{r ggplot visualizations}

TX_outage_count <- ggplot(outage_group_TX,
                          aes(x = date,
                              y = outage_count))+
  geom_point(size = 2, alpha = 0.6)+
  geom_line()+
  geom_smooth(method = "lm", se = FALSE, color = "blue")+
  ylim(0,3000)+
  labs(title = "Number of Outages in Texas from 2015-2023",
       x = "Year",
       y="Number of Outages")

TX_outage_count
  
TX_outage_count_month <- outage_group_TX %>% 
  filter(month != 0) %>% 
  ggplot(aes(x = factor(month,
                        levels=1:12,
                        labels=month.abb),
                             y = outage_count,
                             color = year))+
  geom_point(size = 2, alpha = 0.6)+
  scale_colour_viridis(option = "mako", direction = -1)+
  labs(title = "Number of Outages in Texas by Month from 2015-2023",
       x = "Month",
       y="Number of Outages")

TX_outage_count_month

TX_outage_duration <- outage_group_TX %>% 
  filter(month != 0) %>% 
  ggplot(aes(x = factor(month,
                        levels=1:12,
                        labels=month.abb),
                             y = max_outage_duration,
                             color = year))+
  geom_point(size = 2, alpha = 0.6)+
  scale_colour_viridis(option = "mako", direction = -1)+
  labs(title = "Outage Duration in Texas from 2015-2023",
       x = "Month",
       y="Outage Duration (min) ")
TX_outage_duration

TX_outage_weighted <- outage_group_TX %>% 
  filter(month != 0) %>% 
  ggplot(aes(x = factor(month,
                        levels=1:12,
                        labels=month.abb),
                             y = customer_weighted_hours,
                             color = year))+
  geom_point(size = 2, alpha = 0.6)+
  scale_colour_viridis(option = "mako", direction = -1)+
  labs(title = "Weighted Outage Duration in Texas from 2015-2023 \n (# of customers * outage time) ",
       x = "Month",
       y="Outage Duration (min) ")+
  ylim(0,50000000)
  
TX_outage_weighted

```


```{r time series analysis}
#time series object
Outage_count_ts <- ts(outage_group_TX$outage_count, 
                      start = c(2015,1), 
                      end = c(2023, 12),
                      frequency = 12)

# Generate the decomposition
Outage_count_Decomposed <- stl(Outage_count_ts, s.window = "periodic")
# Visualize the decomposed series. 
plot(Outage_count_Decomposed)

# Extract the components and turn them into data frames
Outage_count_Components <- as.data.frame(Outage_count_Decomposed$time.series[,1:3])

Outage_count_Components <- mutate(Outage_count_Components,
        Observed = outage_group_TX$outage_count,     
        Date = outage_group_TX$date)

# Visualize how the trend maps onto the data
ggplot(Outage_count_Components) +
  geom_line(aes(y = Observed, x = Date),  size = 0.25) +
  geom_line(aes(y = trend, x = Date), color = "#c13d75ff") +
  geom_hline(yintercept = 0, lty = 2)+
  ylim (-100,6000)+
  labs(title = "Trend Component of the Texas Power Outage ",
       x = "Year",
       y=" Number of Outages ")

# Visualize how the seasonal cycle maps onto the data
ggplot(Outage_count_Components) +
  geom_line(aes(y = Observed, x = Date),  size = 0.25) +
  geom_line(aes(y = seasonal, x = Date), color = "#c13d75ff") +
  geom_hline(yintercept = 0, lty = 2)+
    ylim (-100,7500)

```

