---
title: "Data_Analysis_PA"
author: "Addisen Antonucci"
date: "2025-12-10"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##  Setting Up
```{r}
#load packages
library(tidyverse)
library(lubridate)
library(trend)
library(zoo)
library(Kendall)
library(tseries)
library(here)

#read in processed PA data
outage_group_PA <- read.csv(here('Data/Processed/outage_group_PA.csv'), 
                    stringsAsFactors = TRUE)
#Set Theme
mytheme <- theme_classic(base_size = 14) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top")
theme_set(mytheme)

#Format Date  
outage_group_PA$date <- ymd(outage_group_PA$date)

```

#Initial Oberservations
```{r}
#Outages by Month
monthly_outages_PA <- outage_group_PA %>%
  mutate(
    year = year(date),
    month = month(date),
    year_month = as.Date(paste(year, month, "01", sep = "-"))
  ) %>%
  group_by(year_month) %>%
  summarise(outage_count = sum(outage_count))

outage_group_PA <- outage_group_PA %>%
  mutate(
    year = year(date),
    month = month(date)
  )

# Monthly plot
PA_monthly_plot <- outage_group_PA %>% 
  ggplot(aes(
    x = factor(month, levels = 1:12, labels = month.abb),
    y = outage_count,
    color = factor(year)  # factor ensures discrete colors
  )) +
  geom_point(size = 2, alpha = 0.7) +
  scale_color_viridis(
    option = "mako", 
    direction = -1,
    discrete = TRUE  # important for discrete years
  ) +
  labs(
    title = "Number of Power Outages in Pennsylvania by Month (2015-2023)",
    y = "Number of Outages",
    x = "Month",
    color = "Year"
  ) +
  theme_classic(base_size = 14)

PA_monthly_plot

# By Year
yearly_outages_PA <- outage_group_PA %>%
  mutate(year = year(date)) %>%
  group_by(year) %>%
  summarise(outage_count = sum(outage_count, na.rm = TRUE))

# Plot yearly outages
ggplot(yearly_outages_PA, aes(x = year, y = outage_count)) +
  geom_col(fill = "#c13d75ff") +       
  geom_line(aes(group = 1), color = "blue", size = 1) + 
  geom_point(color = "blue", size = 2) +
  labs(x = "Year", y = "Total Outage Count",
       title = "Yearly Total Outages in Pennsylvania") +
  scale_y_continuous(labels = scales::comma) +
  theme_classic(base_size = 14)


```


##  How have outage frequencies changed over time?
###  Time Series of monthly_outages
```{r}
#Creating time Series Objects
Outages_ts_PA <- ts(monthly_outages_PA$outage_count, 
                    start = c(2015,1), end =c(2023,12), frequency = 12)

#Visualize Decomposed Series
Outage_Decomposed_PA <- stl(Outages_ts_PA, s.window = "periodic")

plot(Outage_Decomposed_PA)

##Is there Seaonality?
#Extracting components into Data Frame
Outage_components_PA<-as.data.frame(Outage_Decomposed_PA$time.series[,1:3])

Outage_components_PA <- mutate(Outage_components_PA,
        Observed = monthly_outages_PA$outage_count,     
        Date = monthly_outages_PA$year_month)

#Visualize the trends
ggplot(Outage_components_PA)+
  geom_line(aes(y = Observed, x = Date),  size = 0.25) +
  geom_line(aes(y = trend, x = Date), color = "#c13d75ff") +
  geom_hline(yintercept = 0, lty = 2) +
  xlab("Date")
  ylab("Outages")
  
#Visualize seasonal Component 
ggplot(Outage_components_PA) +
  geom_line(aes(x = Date, y = seasonal), color = "#c13d75ff") +
  geom_hline(yintercept = 0, lty = 2) +
  labs(y = "Seasonal Component", x = "Date")

Outage_components_PA$Month <- month(Outage_components_PA$Date)


#seasonal by month
ggplot(Outage_components_PA) +
  geom_line(aes(
    x = factor(Month, levels = 1:12, labels = month.abb),
    y = seasonal,
    group = year(Date)
  ), color = "#c13d75ff") +
  geom_hline(yintercept = 0, lty = 2) +
  labs(x = "Month", y = "Seasonal Component",
  title = "Seasonal Cycle of Outages in Pennsylvania")


#Mann-Kendall Seasonality Test
Outages_PA_SMK <- Kendall::SeasonalMannKendall(Outages_ts_PA)
Outages_PA_SMK
summary(Outages_PA_SMK)
#p-value is 0.009

#Remove Seasonal
PA_outage_non_seas <- Outages_ts_PA - Outage_components_PA$seasonal

PA_outage_MK_noseason <- trend::mk.test(PA_outage_non_seas)
PA_outage_MK_noseason
#p-value is 0.002
```

##Time Series Analysis for customer_weighted_hours
```{r}
# Aggregate monthly
monthly_cwh_PA <- outage_group_PA %>%
  mutate(
    year = year(date),
    month = month(date),
    year_month = as.Date(paste(year, month, "01", sep = "-"))) %>%
  group_by(year_month) %>%
  summarise(customer_weighted_hours = sum(customer_weighted_hours, na.rm = TRUE))

#Initla Obseravtions of customer-weighted hours
ggplot(monthly_cwh_PA, aes(x = year_month, y = customer_weighted_hours)) +
  geom_line() +
  labs(x = "Year", y = "Customer Weighted Hours",
  title = "Monthly Customer-Weighted Hours (PA)") +
  geom_smooth(method = "lm", color = "#c13d75ff")


# Create time series object
CWH_ts_PA <- ts(
  monthly_cwh_PA$customer_weighted_hours,
  start = c(2015,1), end =c(2023,12), frequency = 12)

# Visualize Decomposed series
CWH_decompose_PA <- stl(CWH_ts_PA, s.window = "periodic")
plot(CWH_decompose_PA)

##Is there Seasonality?
#Extracting components into Data Frame
CWH_components_PA <- as.data.frame(CWH_decompose_PA$time.series[,1:3]) %>%
  mutate(Observed = monthly_cwh_PA$customer_weighted_hours,
    Date = monthly_cwh_PA$year_month,
    Month = month(Date))


# Seasonal Cycle by Month
ggplot(CWH_components_PA) +
  geom_line(aes(
    x = factor(Month, levels = 1:12, labels = month.abb),
    y = seasonal,
    group = year(Date)
  ), color = "#c13d75ff") +
  geom_hline(yintercept = 0) +
  labs(x = "Month", y = "Seasonal Component",
  title = "Seasonal Cycle of Customer-Weighted Hours (PA)")

#Mann-Kendall Seasonality Test
CWH_PA_SMK <- Kendall::SeasonalMannKendall(CWH_ts_PA)
CWH_PA_SMK
summary(CWH_PA_SMK)
#p-value= 0.09

#Remove Seasonal
CWH_non_seas_PA <- CWH_ts_PA - CWH_components_PA$seasonal
CWH_MK_noseason_PA <- trend::mk.test(CWH_non_seas_PA)
CWH_MK_noseason_PA
#p-value=0.06

```

##Time Series of max_outage_duration
```{r}
# Aggregate monthly
monthly_duration_PA <- outage_group_PA %>%
  mutate(
    year = year(date),
    month = month(date),
    year_month = as.Date(paste(year, month, "01", sep = "-"))) %>%
  group_by(year_month) %>%
  summarise(max_outage_duration = max(max_outage_duration, na.rm = TRUE))

#Initial Observations
ggplot(monthly_duration_PA, aes(x = year_month, y = max_outage_duration)) +
  geom_line() +
  labs(x = "Year", y = "Max Outage Duration (hours)",
  title = "Monthly Max Outage Duration (PA)") +
  geom_smooth(method = "lm", color = "#c13d75ff")

# Create time series object
Duration_ts_PA <- ts(
  monthly_duration_PA$max_outage_duration,
  start = c(2015,1), end =c(2023,12), frequency = 12)

# Visualize Decomposed series
Duration_decompose_PA <- stl(Duration_ts_PA, s.window = "periodic")
plot(Duration_decompose_PA)

##Is there Seasonality?
#Extracting components into Data Frame
Duration_components_PA <- as.data.frame(Duration_decompose_PA$time.series[,1:3]) %>%
  mutate( Observed = monthly_duration_PA$max_outage_duration,
    Date = monthly_duration_PA$year_month,
    Month = month(Date))

#Visualize the trends
ggplot(Duration_components_PA) +
  geom_line(aes(x = Date, y = Observed), size = 0.3) +
  geom_line(aes(x = Date, y = trend), color = "#c13d75ff", linewidth = 0.8) +
  labs(x = "Date", y = "Max Outage Duration (hours)",
  title = "Observed vs Trend in Max Outage Duration (PA)") +
  geom_hline(yintercept = 0)

#seasonal by month
ggplot(Duration_components_PA) +
  geom_line(aes(x = Date, y = seasonal), color = "#c13d75ff") +
  geom_hline(yintercept = 0) +
  labs(x = "Date", y = "Seasonal Component",
  title = "Seasonality of Max Outage Duration (PA)")

# Seasonal Cycle by Month
ggplot(Duration_components_PA) +
  geom_line(aes(
    x = factor(Month, levels = 1:12, labels = month.abb),
    y = seasonal,
    group = year(Date)
  ), color = "#c13d75ff") +
  geom_hline(yintercept = 0, linetype = 2) +
  labs(x = "Month", y = "Seasonal Component",
  title = "Seasonal Cycle of Max Outage Duration (PA)")

#Mann-Kendall Seasonality Test

Duration_SMK_PA <- Kendall::SeasonalMannKendall(Duration_ts_PA)
Duration_SMK_PA
summary(Duration_SMK_PA)
#p-value is 0.2


#Remove Seasonal
Duration_non_seas_PA <- Duration_ts_PA - Duration_components_PA$seasonal
Duration_MK_noseason_PA <- trend::mk.test(Duration_non_seas_PA)
Duration_MK_noseason_PA
#p-value= 0.18

```

