---
title: "Initial_Data_Visualization"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(here)
library(viridis)
library(trend)
library(zoo)
```

```{r load data}
#read in CA data from processed folder 
outage_group_CA <- read.csv(here('Data/Processed/outage_group_CA.csv'), 
                            stringsAsFactors = TRUE)

#create new column with month and year combined, first of the month is use to allow for time series analysis  
outage_group_CA <- outage_group_CA %>% 
  mutate(
    date = my(paste0(month, "-", year)))

```

```{r CA data visualization}
#processing: plots, time plot, county spatial plot? 

#yearly plot?
CA_yearly <- outage_group_CA %>% 
  ggplot(
    mapping = aes(
      x= date,
      y = outage_count
      )) +
  geom_point(size = 2, alpha = 0.7)+
  geom_line()+
  geom_smooth(method ="lm")+
  labs(
    title = "Number of Power Outages in California from 2015 to 2023",
    y = "Number of Outages",
    x = "Year"
  )

CA_yearly

#monthly plot (for data visualization)
CA_monthly_plot <- outage_group_CA %>% 
  ggplot(
    mapping = aes(
      x=factor(
      month,
      levels=1:12,
      labels=month.abb),
      y = outage_count,
      color = year)
    ) +
 geom_point(size = 2, alpha = 0.7)+
 scale_color_viridis(
   option = "mako", 
   direction = -1)+
  labs(
    title = "Number of Power Outages in California by Month from 2015 to 2023",
    y = "Number of Outages",
    x = "Month",
    color = "Year",
  )

CA_monthly_plot

CA_monthly_duration_plot <- outage_group_CA %>% 
  ggplot(
    mapping = aes(
      x=factor(
      month,
      levels=1:12,
      labels=month.abb),
      y = max_outage_duration,
      color = year)
    ) +
 geom_point(size = 2, alpha = 0.7)+
 scale_color_viridis(
   option = "mako", 
   direction = -1)+
  labs(
    title = "Maximum Duration of Power Outages in California by Month from 2015 to 2023",
    y = "Maximum Outage Duration (hours)",
    x = "Month",
    color = "Year",
  )

CA_monthly_duration_plot 

CA_weighted_customers_plot <- outage_group_CA %>% 
  ggplot(
    mapping = aes(
      x=factor(
      month,
      levels=1:12,
      labels=month.abb),
      y = customer_weighted_hours,
      color = year)
    ) +
 geom_point(size = 2, alpha = 0.7)+
 scale_color_viridis(
   option = "mako", 
   direction = -1)+
  labs(
    title = "Customer Weighted Hours of Power Outages in California by Month from 2015 to 2023",
    y = "Customer Weighted Hours",
    x = "Month",
    color = "Year",
  )

CA_weighted_customers_plot

```

```{r Time Series Analysis }
#define first day and first year values 
f_month <- month(first(outage_group_CA$date))
f_year <- year(first(outage_group_CA$date))

#create time series object 
CA_outage_ts <- 
  ts(outage_group_CA$outage_count, 
     start = c(f_year, f_month), 
     frequency = 12)

#decompose and plot
CA_outage_decompose <- stl(CA_outage_ts, 
                           s.window = "periodic")
plot(CA_outage_decompose)

#run monotonic trend analysis 
CA_outage_trend <- trend::smk.test(CA_outage_ts)
CA_outage_trend

summary(CA_outage_trend)


```

```{r remove seasonality trend??}
#remove seasonality trend?? and re=run MK test 
#could we remove the other parts to just look at the seasonal trend??
#extract the components of each series into a df
CA_outage_compon <- 
  as.data.frame(CA_outage_decompose$time.series[,1:3])

#remove seasonal 
CA_outage_non_seas <- 
  CA_outage_ts - CA_outage_compon[,1]

#rerun MK
CA_outage_trend_noseasons <- trend::mk.test(CA_outage_non_seas)
CA_outage_trend_noseasons

#remove trend 
CA_outage_seasonal <- 
  CA_outage_ts - CA_outage_compon[,2]

CA_outage_trend_seasonal <- trend::mk.test(CA_outage_seasonal)
CA_outage_trend_seasonal

```


```{r Results Visualization}
#plot of monthly outages 


```

