---
title: "Multi_state_Analysis"
author: "Addisen Antonucci"
date: "2025-12-11"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(lubridate)
```

```{r}
###Seasonal Cycle Combined
#California Seasonal Cycle
outage_seas_month_vis_CA <- ggplot(CA_outage_components) +
  geom_line(aes(y = seasonal, 
                x=factor(
                  Month,
                  levels=1:12,
                  labels=month.abb), 
                group = year(Date)), 
                color = "red") +
  geom_hline(yintercept = 0, lty = 2) +
  labs(x = "Month", 
       y = "# of outages",
       title = "Seasonal Cycle of Power Outages in California")

outage_seas_month_vis_CA

#Pennsylvania seasonal cycle
ggplot(Outage_components_PA) +
  geom_line(aes(
    x = factor(Month, levels = 1:12, labels = month.abb),
    y = seasonal,
    group = year(Date)
  ), color = "purple") +
  geom_hline(yintercept = 0) +
  labs(x = "Month", y = "# of outages",
  title = "Seasonal Cycle of Outages in Pennsylvania")+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r seas_all, fig.cap="Seasonal cycle of power outages in California, Florida, Pennsylvania, and Texas (2015-2023 combined).}
#Seasonal Cycle combined
# Add a column for states () Need to add FL and TX)
CA_outage_combined <- CA_outage_components %>%
  mutate(State = "CA")

PA_Outage_combined <- Outage_components_PA %>%
  mutate(State = "PA")

TX_Outage_combined <- TXOutage_count_Components %>%
  mutate(State = "TX")

FL_Outage_combined <- monthly_outages_FL.components %>%
  mutate(State = "FL",
         Month = as.numeric(outage_group_FL$month),)

# Combine the datasets
combined_data <- bind_rows(CA_outage_combined, PA_Outage_combined, TX_Outage_combined, FL_Outage_combined)

# Plot together
ggplot(combined_data) +
  geom_line(aes(
    x = factor(Month, levels = 1:12, labels = month.abb),
    y = seasonal,
    group = interaction(year(Date), State),
    color = State)) +
  geom_hline(yintercept = 0) +
  labs(
    x = "Month",
    y = "# of outages",
    title = "Seasonal Cycle of Power Outages") +
  scale_color_manual(values = c(
  "CA" = "red",
  "PA" = "purple",
  "TX" = "blue",
  "FL" = "darkgreen"
))

```

```{r trend_all, fig.cap="Nonseasonal trend of power outages in California, Florida, Pennsylvania, and Texas."}

# Add a column for states 
CA_nonseas_combined <- CA_outage_components %>%
  mutate(State = "CA",
         nonseas = trend + remainder)

PA_nonseas_combined <- Outage_components_PA %>%
  mutate(State = "PA", 
         nonseas = trend + remainder)

TX_nonseas_combined <- TXOutage_count_Components %>%
  mutate(State = "TX", 
         nonseas = trend + remainder)

FL_nonseas_combined <- monthly_outages_FL.components %>%
  mutate(State = "FL",
         nonseas = trend + remainder)

# Combine the datasets
nonseas_combined_data <- bind_rows(CA_nonseas_combined, PA_nonseas_combined, TX_nonseas_combined, FL_nonseas_combined)

ggplot(nonseas_combined_data) +
  geom_point(aes(
    x = Date,
    y = nonseas,
    color = State)) +
  labs(
    x = "Month",
    y = "# of outages",
    title = "Trend of Power Outages") +
  scale_color_manual(values = c(
  "CA" = "red",
  "PA" = "purple",
  "TX" = "blue",
  "FL" = "darkgreen"
))

nonseas_combined <- nonseas_combined_data %>% 
  ggplot(
    aes(
      x = Date,
      y = nonseas,
      color = State)) +
  geom_point(size = 2, alpha = 0.7)+
  geom_line()+
  geom_smooth(method ="lm", se = FALSE, color = "red") +
  labs(
    x = "Month",
    y = "# of outages",
    title = "Trend of Power Outages") +
  scale_color_manual(values = c(
  "CA" = "red",
  "PA" = "purple",
  "TX" = "blue",
  "FL" = "darkgreen"))

nonseas_combined

combined_NonSeasonal.Plot <- ggplot(NULL) +
  scale_y_log10(limits = c(0.25, 1200)) +
  geom_point(data = NonSeasonalDischarge.Daily, aes(Date, Seasonality_Removed), 
             color = "forestgreen", alpha = 0.05) +
  geom_smooth(data = NonSeasonalDischarge.Daily, aes(Date, Seasonality_Removed),
              method = "lm", color = "forestgreen") +
  geom_point(data = florida_hurricane_Decomposed_Components, 
             aes(x = Date, y = data), color = "deeppink1", alpha = 0.05) +
  geom_smooth(data = florida_hurricane_Decomposed_Components, 
             aes(x = Date, y = data), method = "lm", color = "deeppink1") +
  geom_point(data = NY_Combine_Nonseasonal, aes(x = Date, y = Nonseasonal), 
             color = "turquoise4", alpha = 0.05) + 
  geom_smooth(data = NY_Combine_Nonseasonal, aes(x = Date, y = Nonseasonal), 
              method = "lm", color = "turquoise4") +
  labs(x = "Date", y = "Non-Seasonal Daily Discharge (cfs)", 
       title = "Non-Seasonal Mean Daily Discharge During Hurricane Seasons") +
  scale_x_date(date_labels = "%Y", date_breaks = "2 year") +
  theme(axis.text.x = element_text(angle = 90))
plot(combined_NonSeasonal.Plot)

CA_yearly <- outage_group_CA %>% 
  ggplot(
    mapping = aes(
      x= date,
      y = outage_count
      )) +
  geom_point(size = 2, alpha = 0.7)+
  geom_line()+
  geom_smooth(method ="lm", se = FALSE, color = "red") +
  labs(
    title = "Number of Power Outages in California from 2015 to 2023",
    y = "Number of Outages",
    x = "Year"
  )


```

