---
title: 'Power Outage Trends in California, Florida, Pennsylvania, and Texas from 2015 to 2023'
subtitle: 'https://github.com/sarahj-hall/Antonucci_Hall_Huang_Kuehn_ENV872_FinalProject.git'
authors: 'Addisen Antonucci, Sarah Hall, Carina Huang, and Isabelle Kuehn'
date: 'December 12th, 2025'
output: 
  pdf_document: default
editor_options:
  chunk_output_type: console
---
\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Load your packages
library(tidyverse)
library(dplyr)
library(here)
library(lubridate)
library(viridis)
library(zoo)

# Set your working directory
here()

# Set ggplot theme
mytheme <- theme_classic(base_size = 12) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top")
theme_set(mytheme)

#set global chunk options
knitr::opts_chunk$set()

# Load your datasets

#load CA data

#format date column

```


# Rationale and Research Questions
Write 1-2 paragraph(s) detailing the rationale for your study. This should include both the context of the topic as well as a rationale for your choice of dataset (reason for location, variables, etc.). You may choose to include citations if you like (optional).

At the end of your rationale, introduce a numbered list of your questions (or an overarching question and sub-questions).

- damage of outages (health, financial)
- increasing climate related weather events, vulnerable power system infrastructure 
- selected four states, tried to spread out geographically but also selected states with the highest power outages/most impacted by recent extreme climate events. Texas, California, Florida, and Pennsylvania 



\newpage

# Dataset Information
Provide information on how the dataset for this analysis were collected, the data contained in the dataset, and any important pieces of information that are relevant to your analyses. This section should contain much of same information as the metadata file for the dataset but formatted in a way that is more narrative.

Describe how you wrangled your dataset in a format similar to a methods section of a journal article.

Add a table that summarizes your data structure (variables, units, ranges and/or central tendencies, data source if multiple are used, etc.). This table can be made in markdown text or inserted as a kable function in an R chunk. If the latter, do not include the code used to generate your table.


\newpage

# Exploratory Analysis 
Insert exploratory visualizations of your dataset. This may include, but is not limited to, graphs illustrating the distributions of variables of interest and/or maps of the spatial context of your dataset. Format your R chunks so that graphs are displayed but code is not displayed. Accompany these graphs with text sections that describe the visualizations and provide context for further analyses.

Each figure should be accompanied by a caption, and each figure should be referenced within the text.

Scope: think about what information someone might want to know about the dataset before analyzing it statistically. How might you visualize this information?

\newpage

# Analysis
Insert visualizations and text describing your main analyses. Format your R chunks so that graphs are displayed but code and other output is not displayed. Instead, describe the results of any statistical tests in the main text (e.g., “Variable x was significantly different among y groups (ANOVA; df = 300, F = 5.55, p < 0.0001)”). Each paragraph, accompanied by one or more visualizations, should describe the major findings and how they relate to the question and hypotheses. Divide this section into subsections, one for each research question.

Each figure should be accompanied by a caption, and each figure should be referenced within the text

**trying to figure out the best organization for this.. where is the best place for the seasonality component? 

## Question 1: How has the frequency of power outages changed over time?
### 1.1 California 
### 1.2 Florida 
### 1.3 Pennsylvania 
### 1.4 Texas 
### 1.5 Comparision between States

## Question 2: Is there a seasonal trend? Are certain months more prone to outages? 
### 2.1 California 
### 2.2 Florida 
### 2.3 Pennsylvania 
### 2.4 Texas 
### 2.5 Comparision between States

## Question 3: How has the length of power outages changed over time?  
### 3.1 California 
### 3.2 Florida 
### 3.3 Pennsylvania 
### 3.4 Texas 
### 3.5 Comparision between States

\newpage

# Summary and Conclusions
Summarize your major findings from your analyses in a few paragraphs. What conclusions do you draw from your findings? Relate your findings back to the original research questions and rationale.

\newpage

# References
<add references here if relevant, otherwise delete this section> 
